import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
import UseServiceWorker from "@/components/registerServiceWorker"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Web2 PWA Clicker Game",
	description: "Generated by create next app",
	manifest: "/manifest.json",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<UseServiceWorker />
				<Navbar />
				{children}
			</body>
		</html>
	)
}
